# SPDX-FileCopyrightText: Hathor Labs
# SPDX-License-Identifier: Apache-2.0

newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Requires nightly:
# format_code_in_doc_comments = true
# format_macro_matchers = true
# group_imports = StdExternalCrate
# imports_granularity = "Module"
# reorder_impl_items = true
