P2PKH_VERSION_BYTE: x49
MULTISIG_VERSION_BYTE: x87
NETWORK_NAME: ide-testnet
BOOTSTRAP_DNS: []

# Genesis stuff (using testnet-golf values but not critical for IDE)
GENESIS_OUTPUT_SCRIPT: 76a914a584cf48b161e4a49223ed220df30037ab740e0088ac
GENESIS_BLOCK_TIMESTAMP: 1577836800
GENESIS_BLOCK_NONCE: 826272
GENESIS_BLOCK_HASH: 0000033139d08176d1051fb3a272c3610457f0c7f686afbe0afe3d37f966db85
GENESIS_TX1_NONCE: 190
GENESIS_TX1_HASH: 00e161a6b0bee1781ea9300680913fb76fd0fac4acab527cd9626cc1514abdc9
GENESIS_TX2_NONCE: 115
GENESIS_TX2_HASH: 00975897028ceb037307327c953f5e7ad4d3f42402d71bd3d11ecb63ac39f01a

# Enable nano contracts for IDE
ENABLE_NANO_CONTRACTS: enabled

# Nano contracts settings for IDE
NC_INITIAL_FUEL_TO_CALL_METHOD: 1000000
NC_MEMORY_LIMIT_TO_CALL_METHOD: 104857600  # 100MB
NC_INITIAL_FUEL_TO_LOAD_BLUEPRINT_MODULE: 100000
NC_MEMORY_LIMIT_TO_LOAD_BLUEPRINT_MODULE: 52428800  # 50MB
NC_ON_CHAIN_BLUEPRINT_CODE_MAX_SIZE_COMPRESSED: 1048576  # 1MB
NC_ON_CHAIN_BLUEPRINT_CODE_MAX_SIZE_UNCOMPRESSED: 10485760  # 10MB

# tx weight parameters. With these settings tx weight is always 8
MIN_TX_WEIGHT_K: 0
MIN_TX_WEIGHT_COEFFICIENT: 0
MIN_TX_WEIGHT: 8