codecov:
  branch: dev

coverage:
  # https://docs.codecov.com/docs/coverage-configuration
  range: "80...90"
  # https://docs.codecov.io/docs/commit-status
  status:
    # TODO: re-enable patch in the future
    patch: off
    project:
      default:
        # minimum coverage ratio that the commit must meet to be considered a success
        target: 83%
        if_ci_failed: error
        only_pulls: true

github_checks:
  annotations: true
