// Hand-written entry point. The native binding (index.js) is generated by @napi-rs/cli;
// JavaScript cannot declare [Symbol.toPrimitive] from Rust, so we attach it here so that
// the relational operators <, >, <=, >= work on TokenAmount / TokenBalance.
//
// For the 'string' hint we defer to toString() (the Rust Debug form). For 'number' and
// 'default' we return the underlying value as a bigint so ordering compares correctly.
// Note: == / === remain reference identity (use .eq()); + / - return bigint (use .add/.sub).
//
// Named exports are listed explicitly so that Node's CJS-to-ESM static analysis can
// detect them and expose them as named ESM imports (same pattern as the generated index.js).

const binding = require('./index.js')

binding.TokenAmount.prototype[Symbol.toPrimitive] = function (hint) {
  return hint === 'string' ? this.toString() : this.normalized()
}

binding.TokenBalance.prototype[Symbol.toPrimitive] = function (hint) {
  return hint === 'string' ? this.toString() : this.raw()
}

module.exports = binding
module.exports.TokenAmount = binding.TokenAmount
module.exports.TokenBalance = binding.TokenBalance
module.exports.TokenAmountVersion = binding.TokenAmountVersion
