// Hand-written Node entry point. The native binding (index.js) is generated by @napi-rs/cli.
// `applyOperators` attaches [Symbol.toPrimitive] — which JavaScript cannot declare from Rust — so
// the relational operators <, >, <=, >= work on UnsignedAmount / SignedAmount. The same shared
// patch is applied to the browser/wasm entry (browser-wrapper.mjs), so both behave identically.
//
// Named exports are listed explicitly so that Node's CJS-to-ESM static analysis can detect them
// and expose them as named ESM imports (same pattern as the generated index.js).

const binding = require('./index.js')
const applyOperators = require('./apply-operators.cjs')

applyOperators(binding)

module.exports = binding
module.exports.UnsignedAmount = binding.UnsignedAmount
module.exports.SignedAmount = binding.SignedAmount
module.exports.TokenAmountVersion = binding.TokenAmountVersion
