# SPDX-FileCopyrightText: Hathor Labs
# SPDX-License-Identifier: Apache-2.0

# Re-export all exceptions from hathorlib for backward compatibility
from hathorlib.exceptions import TxValidationError  # noqa: F401
from hathorlib.nanocontracts.exception import (  # noqa: F401
    BlueprintDoesNotExist,
    BlueprintSyntaxError,
    NanoContractDoesNotExist,
    NCAlreadyInitializedContractError,
    NCAttributeError,
    NCContractCreationAtMempool,
    NCContractCreationNotFound,
    NCContractCreationVoided,
    NCDisabledBuiltinError,
    NCFail,
    NCForbiddenAction,
    NCForbiddenReentrancy,
    NCInsufficientFunds,
    NCInvalidAction,
    NCInvalidContext,
    NCInvalidContractId,
    NCInvalidFee,
    NCInvalidFeePaymentToken,
    NCInvalidInitializeMethodCall,
    NCInvalidMethodCall,
    NCInvalidPubKey,
    NCInvalidPublicMethodCallFromView,
    NCInvalidSeqnum,
    NCInvalidSignature,
    NCInvalidSyscall,
    NCMethodNotFound,
    NCNumberOfCallsExceeded,
    NCRecursionError,
    NCSerializationArgTooLong,
    NCSerializationError,
    NCSerializationTypeError,
    NCTokenAlreadyExists,
    NCTxValidationError,
    NCTypeError,
    NCUninitializedContractError,
    NCViewMethodError,
    OCBBlueprintNotConfirmed,
    OCBInvalidBlueprintVertexType,
    OCBInvalidScript,
    OCBOutOfFuelDuringLoading,
    OCBOutOfMemoryDuringLoading,
    OCBPubKeyNotAllowed,
    UnknownFieldType,
)
