# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/p2p.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/p2p.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/p2p.proto\x12\x03p2p\"\x07\n\x05\x45mpty\"\x1a\n\tBoolValue\x12\r\n\x05value\x18\x01 \x01(\x08\"\x1c\n\x0bStringValue\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\nBytesValue\x12\r\n\x05value\x18\x01 \x01(\x0c\"\x1b\n\nInt32Value\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1c\n\nStringList\x12\x0e\n\x06values\x18\x01 \x03(\t2\xfb\x03\n\nP2PManager\x12\x34\n\x11IsPeerWhitelisted\x12\x0f.p2p.BytesValue\x1a\x0e.p2p.BoolValue\x12\x35\n\x16GetEnabledSyncVersions\x12\n.p2p.Empty\x1a\x0f.p2p.StringList\x12/\n\x10GetVerifiedPeers\x12\n.p2p.Empty\x1a\x0f.p2p.StringList\x12-\n\rOnReceivePeer\x12\x10.p2p.StringValue\x1a\n.p2p.Empty\x12-\n\rOnPeerConnect\x12\x10.p2p.StringValue\x1a\n.p2p.Empty\x12+\n\x0bOnPeerReady\x12\x10.p2p.StringValue\x1a\n.p2p.Empty\x12\x30\n\x10OnPeerDisconnect\x12\x10.p2p.StringValue\x1a\n.p2p.Empty\x12\x30\n\x0cGetRandBytes\x12\x0f.p2p.Int32Value\x1a\x0f.p2p.BytesValue\x12\x32\n\x0fIsPeerConnected\x12\x0f.p2p.BytesValue\x1a\x0e.p2p.BoolValue\x12,\n\rSendTxToPeers\x12\x0f.p2p.BytesValue\x1a\n.p2p.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.p2p_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=25
  _globals['_EMPTY']._serialized_end=32
  _globals['_BOOLVALUE']._serialized_start=34
  _globals['_BOOLVALUE']._serialized_end=60
  _globals['_STRINGVALUE']._serialized_start=62
  _globals['_STRINGVALUE']._serialized_end=90
  _globals['_BYTESVALUE']._serialized_start=92
  _globals['_BYTESVALUE']._serialized_end=119
  _globals['_INT32VALUE']._serialized_start=121
  _globals['_INT32VALUE']._serialized_end=148
  _globals['_STRINGLIST']._serialized_start=150
  _globals['_STRINGLIST']._serialized_end=178
  _globals['_P2PMANAGER']._serialized_start=181
  _globals['_P2PMANAGER']._serialized_end=688
# @@protoc_insertion_point(module_scope)
