def sum_as_string(a: int, b: int) -> str:
    ...

class TokenBalance:
    def __new__(cls, balance: int = 0) -> TokenBalance: ...

    def raw(self) -> int: ...
    def to_balance(self) -> TokenBalance: ...
    def to_amount(self) -> TokenAmount: ...

    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

    def __add__(self, other: TokenBalance) -> TokenBalance: ...
    def __sub__(self, other: TokenBalance) -> TokenBalance: ...
    def __neg__(self) -> TokenBalance: ...
    def __pos__(self) -> TokenBalance: ...

    def __lt__(self, other: TokenBalance) -> bool: ...
    def __le__(self, other: TokenBalance) -> bool: ...
    def __eq__(self, other: TokenBalance) -> bool: ...
    def __ne__(self, other: TokenBalance) -> bool: ...
    def __gt__(self, other: TokenBalance) -> bool: ...
    def __ge__(self, other: TokenBalance) -> bool: ...

class TokenAmount:
    @staticmethod
    def set_normalization_factor(*, v1_decimal_places: int, v2_decimal_places: int) -> None: ...

    @staticmethod
    def get_normalization_factor() -> int: ...

    @staticmethod
    def from_v1(amount: int) -> TokenAmount: ...

    @staticmethod
    def from_v2(amount: int) -> TokenAmount: ...

    @staticmethod
    def from_version(amount: int, *, version: int) -> TokenAmount: ...

    @staticmethod
    def zero() -> TokenAmount: ...

    def is_v1(self) -> bool: ...
    def is_v2(self) -> bool: ...
    def normalized(self) -> int: ...
    def raw(self) -> int: ...
    def to_balance(self) -> TokenBalance: ...
    def to_v1(self) -> TokenAmount: ...
    def maybe_to_v1(self) -> TokenAmount | None: ...
    def to_v2(self) -> TokenAmount: ...
    def to_version(self, version: int) -> TokenAmount: ...

    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

    def __add__(self, other: TokenAmount) -> TokenAmount: ...
    def __sub__(self, other: TokenAmount) -> TokenAmount: ...

    def __lt__(self, other: TokenAmount) -> bool: ...
    def __le__(self, other: TokenAmount) -> bool: ...
    def __eq__(self, other: TokenAmount) -> bool: ...
    def __ne__(self, other: TokenAmount) -> bool: ...
    def __gt__(self, other: TokenAmount) -> bool: ...
    def __ge__(self, other: TokenAmount) -> bool: ...
