def sum_as_string(a: int, b: int) -> str:
    ...

class SignedAmount:
    def __new__(cls, amount: int = 0) -> SignedAmount: ...

    def raw(self) -> int: ...
    def to_signed(self) -> SignedAmount: ...
    def to_unsigned(self) -> UnsignedAmount: ...

    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

    def __add__(self, other: SignedAmount) -> SignedAmount: ...
    def __sub__(self, other: SignedAmount) -> SignedAmount: ...
    def __neg__(self) -> SignedAmount: ...
    def __pos__(self) -> SignedAmount: ...

    def __lt__(self, other: SignedAmount) -> bool: ...
    def __le__(self, other: SignedAmount) -> bool: ...
    def __eq__(self, other: SignedAmount) -> bool: ...
    def __ne__(self, other: SignedAmount) -> bool: ...
    def __gt__(self, other: SignedAmount) -> bool: ...
    def __ge__(self, other: SignedAmount) -> bool: ...

class UnsignedAmount:
    @staticmethod
    def set_normalization_factor(*, v1_decimal_places: int, v2_decimal_places: int) -> None: ...

    @staticmethod
    def get_normalization_factor() -> int: ...

    @staticmethod
    def from_v1(amount: int) -> UnsignedAmount: ...

    @staticmethod
    def from_v2(amount: int) -> UnsignedAmount: ...

    @staticmethod
    def from_version(amount: int, *, version: int) -> UnsignedAmount: ...

    @staticmethod
    def zero() -> UnsignedAmount: ...

    def is_v1(self) -> bool: ...
    def is_v2(self) -> bool: ...
    def normalized(self) -> int: ...
    def raw(self) -> int: ...
    def to_signed(self) -> SignedAmount: ...
    def to_v1(self) -> UnsignedAmount: ...
    def maybe_to_v1(self) -> UnsignedAmount | None: ...
    def to_v2(self) -> UnsignedAmount: ...
    def to_version(self, version: int) -> UnsignedAmount: ...

    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

    def __add__(self, other: UnsignedAmount) -> UnsignedAmount: ...
    def __sub__(self, other: UnsignedAmount) -> UnsignedAmount: ...

    def __lt__(self, other: UnsignedAmount) -> bool: ...
    def __le__(self, other: UnsignedAmount) -> bool: ...
    def __eq__(self, other: UnsignedAmount) -> bool: ...
    def __ne__(self, other: UnsignedAmount) -> bool: ...
    def __gt__(self, other: UnsignedAmount) -> bool: ...
    def __ge__(self, other: UnsignedAmount) -> bool: ...
