#!/bin/bash

# SPDX-FileCopyrightText: Hathor Labs
# SPDX-License-Identifier: Apache-2.0

BASENAME=`basename $0`

if [ $# -ne 1 ]; then
	echo "usage: ${BASENAME} <prof_file>"
	exit 1
fi

FILE=$1

exec python -m pstats $FILE
