/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Derive a deterministic NUMS generator for a token UID. */
export declare function deriveAssetTag(tokenUid: Buffer): Buffer
/** Return the HTR asset tag (token_uid = [0; 32]). */
export declare function htrAssetTag(): Buffer
/** Derive a raw Tag from token UID (for surjection proofs). */
export declare function deriveTag(tokenUid: Buffer): Buffer
/** Create a blinded asset commitment (Generator) from a Tag and blinding factor. */
export declare function createAssetCommitment(tagBytes: Buffer, rAsset: Buffer): Buffer
/** Create a Pedersen commitment. */
export declare function createCommitment(amount: bigint, blinding: Buffer, generator: Buffer): Buffer
/** Create a trivial (zero-blinding) Pedersen commitment. */
export declare function createTrivialCommitment(amount: bigint, generator: Buffer): Buffer
/** Verify that sum of positive commitments equals sum of negative commitments. */
export declare function verifyCommitmentsSum(positive: Array<Buffer>, negative: Array<Buffer>): boolean
/** Create a Borromean range proof. */
export declare function createRangeProof(amount: bigint, blinding: Buffer, commitment: Buffer, generator: Buffer, message?: Buffer | undefined | null, nonce?: Buffer | undefined | null): Buffer
/** Verify a Borromean range proof. */
export declare function verifyRangeProof(proof: Buffer, commitment: Buffer, generator: Buffer): boolean
/** Rewind a Borromean range proof to recover the committed value, blinding factor, and message. */
export interface RewindResult {
  value: bigint
  blindingFactor: Buffer
  message: Buffer
}
export declare function rewindRangeProof(proof: Buffer, commitment: Buffer, nonce: Buffer, generator: Buffer): RewindResult
/** Validate that bytes represent a valid Pedersen commitment (curve point). */
export declare function validateCommitment(data: Buffer): boolean
/** Validate that bytes represent a valid generator (curve point). */
export declare function validateGenerator(data: Buffer): boolean
/** Create a surjection proof. */
export declare function createSurjectionProof(codomainTag: Buffer, codomainBlindingFactor: Buffer, domain: Array<SurjectionDomainEntry>): Buffer
export interface SurjectionDomainEntry {
  generator: Buffer
  tag: Buffer
  blindingFactor: Buffer
}
/** Verify a surjection proof. */
export declare function verifySurjectionProof(proof: Buffer, codomain: Buffer, domain: Array<Buffer>): boolean
export interface TransparentEntry {
  amount: bigint
  tokenUid: Buffer
}
/** Verify the homomorphic balance equation. */
export declare function verifyBalance(transparentInputs: Array<TransparentEntry>, shieldedInputs: Array<Buffer>, transparentOutputs: Array<TransparentEntry>, shieldedOutputs: Array<Buffer>): boolean
/** Compute the balancing blinding factor for the last output. */
export declare function computeBalancingBlindingFactor(value: bigint, generatorBlindingFactor: Buffer, inputs: Array<BlindingEntry>, otherOutputs: Array<BlindingEntry>): Buffer
export interface BlindingEntry {
  value: bigint
  valueBlindingFactor: Buffer
  generatorBlindingFactor: Buffer
}
/** Generate a random 32-byte blinding factor (valid secp256k1 scalar). */
export declare function generateRandomBlindingFactor(): Buffer
/**
 * Generate a fresh ephemeral secp256k1 key pair.
 *
 * Returns (private_key_bytes: 32B, compressed_pubkey_bytes: 33B).
 */
export interface EphemeralKeypair {
  privateKey: Buffer
  publicKey: Buffer
}
export declare function generateEphemeralKeypair(): EphemeralKeypair
/**
 * Compute ECDH shared secret: SHA256(version_byte || x_coordinate).
 *
 * Uses libsecp256k1's standard ECDH derivation.
 * Returns 32-byte shared secret.
 */
export declare function deriveEcdhSharedSecret(privateKey: Buffer, peerPubkey: Buffer): Buffer
/**
 * Derive a deterministic nonce from a shared secret.
 *
 * nonce = SHA256("Hathor_CT_nonce_v1" || shared_secret)
 * Returns 32-byte nonce suitable for use as a range proof nonce key.
 */
export declare function deriveRewindNonce(sharedSecret: Buffer): Buffer
export interface CreatedShieldedOutput {
  ephemeralPubkey: Buffer
  commitment: Buffer
  rangeProof: Buffer
  blindingFactor: Buffer
  assetCommitment?: Buffer
  assetBlindingFactor?: Buffer
}
/**
 * Create a FullShielded output with both value blinding factor and asset blinding factor
 * provided externally. This is needed for the last output in a FullShielded transaction
 * where the balance equation requires pre-computing the vbf using a known abf.
 */
export declare function createShieldedOutputWithBothBlindings(value: bigint, recipientPubkey: Buffer, tokenUid: Buffer, valueBlindingFactor: Buffer, assetBlindingFactor: Buffer): CreatedShieldedOutput
/** Result of creating an AmountShielded output (amount hidden, token visible). */
export interface CreatedAmountShieldedOutput {
  ephemeralPubkey: Buffer
  commitment: Buffer
  rangeProof: Buffer
  blindingFactor: Buffer
}
/**
 * Create an AmountShielded output (amount hidden, token visible).
 *
 * Uses `derive_asset_tag(token_uid)` as the unblinded generator.
 */
export declare function createAmountShieldedOutput(value: bigint, recipientPubkey: Buffer, tokenUid: Buffer, valueBlindingFactor: Buffer): CreatedAmountShieldedOutput
/** Result of rewinding an AmountShielded output. */
export interface RewoundAmountShieldedOutput {
  value: bigint
  blindingFactor: Buffer
}
/** Rewind an AmountShielded output to recover value and blinding factor. */
export declare function rewindAmountShieldedOutput(privateKey: Buffer, ephemeralPubkey: Buffer, commitment: Buffer, rangeProof: Buffer, tokenUid: Buffer): RewoundAmountShieldedOutput
/** Result of rewinding a FullShielded output. */
export interface RewoundFullShieldedOutput {
  value: bigint
  blindingFactor: Buffer
  tokenUid: Buffer
  assetBlindingFactor: Buffer
}
/** Rewind a FullShielded output to recover value, blinding factor, token UID and asset blinding. */
export declare function rewindFullShieldedOutput(privateKey: Buffer, ephemeralPubkey: Buffer, commitment: Buffer, rangeProof: Buffer, assetCommitment: Buffer): RewoundFullShieldedOutput
/** Size of a serialized Pedersen commitment. */
export declare function getCommitmentSize(): number
/** Size of a serialized generator. */
export declare function getGeneratorSize(): number
/** The zero tweak (32 zero bytes). */
export declare function getZeroTweak(): Buffer
