// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(hathor_ct_cryptoFFI)
import hathor_ct_cryptoFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_hathor_ct_crypto_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_hathor_ct_crypto_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct BlindingEntry {
    public var value: UInt64
    public var vbf: Data
    public var gbf: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(value: UInt64, vbf: Data, gbf: Data) {
        self.value = value
        self.vbf = vbf
        self.gbf = gbf
    }
}



extension BlindingEntry: Equatable, Hashable {
    public static func ==(lhs: BlindingEntry, rhs: BlindingEntry) -> Bool {
        if lhs.value != rhs.value {
            return false
        }
        if lhs.vbf != rhs.vbf {
            return false
        }
        if lhs.gbf != rhs.gbf {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(value)
        hasher.combine(vbf)
        hasher.combine(gbf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBlindingEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BlindingEntry {
        return
            try BlindingEntry(
                value: FfiConverterUInt64.read(from: &buf), 
                vbf: FfiConverterData.read(from: &buf), 
                gbf: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: BlindingEntry, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.value, into: &buf)
        FfiConverterData.write(value.vbf, into: &buf)
        FfiConverterData.write(value.gbf, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBlindingEntry_lift(_ buf: RustBuffer) throws -> BlindingEntry {
    return try FfiConverterTypeBlindingEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBlindingEntry_lower(_ value: BlindingEntry) -> RustBuffer {
    return FfiConverterTypeBlindingEntry.lower(value)
}


public struct CreatedShieldedOutput {
    public var ephemeralPubkey: Data
    public var commitment: Data
    public var rangeProof: Data
    public var blindingFactor: Data
    public var assetCommitment: Data?
    public var assetBlindingFactor: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ephemeralPubkey: Data, commitment: Data, rangeProof: Data, blindingFactor: Data, assetCommitment: Data?, assetBlindingFactor: Data?) {
        self.ephemeralPubkey = ephemeralPubkey
        self.commitment = commitment
        self.rangeProof = rangeProof
        self.blindingFactor = blindingFactor
        self.assetCommitment = assetCommitment
        self.assetBlindingFactor = assetBlindingFactor
    }
}



extension CreatedShieldedOutput: Equatable, Hashable {
    public static func ==(lhs: CreatedShieldedOutput, rhs: CreatedShieldedOutput) -> Bool {
        if lhs.ephemeralPubkey != rhs.ephemeralPubkey {
            return false
        }
        if lhs.commitment != rhs.commitment {
            return false
        }
        if lhs.rangeProof != rhs.rangeProof {
            return false
        }
        if lhs.blindingFactor != rhs.blindingFactor {
            return false
        }
        if lhs.assetCommitment != rhs.assetCommitment {
            return false
        }
        if lhs.assetBlindingFactor != rhs.assetBlindingFactor {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(ephemeralPubkey)
        hasher.combine(commitment)
        hasher.combine(rangeProof)
        hasher.combine(blindingFactor)
        hasher.combine(assetCommitment)
        hasher.combine(assetBlindingFactor)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCreatedShieldedOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CreatedShieldedOutput {
        return
            try CreatedShieldedOutput(
                ephemeralPubkey: FfiConverterData.read(from: &buf), 
                commitment: FfiConverterData.read(from: &buf), 
                rangeProof: FfiConverterData.read(from: &buf), 
                blindingFactor: FfiConverterData.read(from: &buf), 
                assetCommitment: FfiConverterOptionData.read(from: &buf), 
                assetBlindingFactor: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: CreatedShieldedOutput, into buf: inout [UInt8]) {
        FfiConverterData.write(value.ephemeralPubkey, into: &buf)
        FfiConverterData.write(value.commitment, into: &buf)
        FfiConverterData.write(value.rangeProof, into: &buf)
        FfiConverterData.write(value.blindingFactor, into: &buf)
        FfiConverterOptionData.write(value.assetCommitment, into: &buf)
        FfiConverterOptionData.write(value.assetBlindingFactor, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreatedShieldedOutput_lift(_ buf: RustBuffer) throws -> CreatedShieldedOutput {
    return try FfiConverterTypeCreatedShieldedOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreatedShieldedOutput_lower(_ value: CreatedShieldedOutput) -> RustBuffer {
    return FfiConverterTypeCreatedShieldedOutput.lower(value)
}


public struct DecryptedShieldedOutput {
    public var value: UInt64
    public var blindingFactor: Data
    public var tokenUid: Data
    public var assetBlindingFactor: Data?
    public var outputType: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(value: UInt64, blindingFactor: Data, tokenUid: Data, assetBlindingFactor: Data?, outputType: String) {
        self.value = value
        self.blindingFactor = blindingFactor
        self.tokenUid = tokenUid
        self.assetBlindingFactor = assetBlindingFactor
        self.outputType = outputType
    }
}



extension DecryptedShieldedOutput: Equatable, Hashable {
    public static func ==(lhs: DecryptedShieldedOutput, rhs: DecryptedShieldedOutput) -> Bool {
        if lhs.value != rhs.value {
            return false
        }
        if lhs.blindingFactor != rhs.blindingFactor {
            return false
        }
        if lhs.tokenUid != rhs.tokenUid {
            return false
        }
        if lhs.assetBlindingFactor != rhs.assetBlindingFactor {
            return false
        }
        if lhs.outputType != rhs.outputType {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(value)
        hasher.combine(blindingFactor)
        hasher.combine(tokenUid)
        hasher.combine(assetBlindingFactor)
        hasher.combine(outputType)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDecryptedShieldedOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DecryptedShieldedOutput {
        return
            try DecryptedShieldedOutput(
                value: FfiConverterUInt64.read(from: &buf), 
                blindingFactor: FfiConverterData.read(from: &buf), 
                tokenUid: FfiConverterData.read(from: &buf), 
                assetBlindingFactor: FfiConverterOptionData.read(from: &buf), 
                outputType: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: DecryptedShieldedOutput, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.value, into: &buf)
        FfiConverterData.write(value.blindingFactor, into: &buf)
        FfiConverterData.write(value.tokenUid, into: &buf)
        FfiConverterOptionData.write(value.assetBlindingFactor, into: &buf)
        FfiConverterString.write(value.outputType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecryptedShieldedOutput_lift(_ buf: RustBuffer) throws -> DecryptedShieldedOutput {
    return try FfiConverterTypeDecryptedShieldedOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecryptedShieldedOutput_lower(_ value: DecryptedShieldedOutput) -> RustBuffer {
    return FfiConverterTypeDecryptedShieldedOutput.lower(value)
}


public struct RewindResult {
    public var value: UInt64
    public var blindingFactor: Data
    public var message: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(value: UInt64, blindingFactor: Data, message: Data) {
        self.value = value
        self.blindingFactor = blindingFactor
        self.message = message
    }
}



extension RewindResult: Equatable, Hashable {
    public static func ==(lhs: RewindResult, rhs: RewindResult) -> Bool {
        if lhs.value != rhs.value {
            return false
        }
        if lhs.blindingFactor != rhs.blindingFactor {
            return false
        }
        if lhs.message != rhs.message {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(value)
        hasher.combine(blindingFactor)
        hasher.combine(message)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRewindResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RewindResult {
        return
            try RewindResult(
                value: FfiConverterUInt64.read(from: &buf), 
                blindingFactor: FfiConverterData.read(from: &buf), 
                message: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: RewindResult, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.value, into: &buf)
        FfiConverterData.write(value.blindingFactor, into: &buf)
        FfiConverterData.write(value.message, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRewindResult_lift(_ buf: RustBuffer) throws -> RewindResult {
    return try FfiConverterTypeRewindResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRewindResult_lower(_ value: RewindResult) -> RustBuffer {
    return FfiConverterTypeRewindResult.lower(value)
}


public struct SurjectionDomainEntry {
    public var generator: Data
    public var tag: Data
    public var blindingFactor: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(generator: Data, tag: Data, blindingFactor: Data) {
        self.generator = generator
        self.tag = tag
        self.blindingFactor = blindingFactor
    }
}



extension SurjectionDomainEntry: Equatable, Hashable {
    public static func ==(lhs: SurjectionDomainEntry, rhs: SurjectionDomainEntry) -> Bool {
        if lhs.generator != rhs.generator {
            return false
        }
        if lhs.tag != rhs.tag {
            return false
        }
        if lhs.blindingFactor != rhs.blindingFactor {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(generator)
        hasher.combine(tag)
        hasher.combine(blindingFactor)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSurjectionDomainEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SurjectionDomainEntry {
        return
            try SurjectionDomainEntry(
                generator: FfiConverterData.read(from: &buf), 
                tag: FfiConverterData.read(from: &buf), 
                blindingFactor: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: SurjectionDomainEntry, into buf: inout [UInt8]) {
        FfiConverterData.write(value.generator, into: &buf)
        FfiConverterData.write(value.tag, into: &buf)
        FfiConverterData.write(value.blindingFactor, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSurjectionDomainEntry_lift(_ buf: RustBuffer) throws -> SurjectionDomainEntry {
    return try FfiConverterTypeSurjectionDomainEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSurjectionDomainEntry_lower(_ value: SurjectionDomainEntry) -> RustBuffer {
    return FfiConverterTypeSurjectionDomainEntry.lower(value)
}


public enum CryptoError {

    
    
    case InvalidInput(msg: String
    )
    case CryptoFailed(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCryptoError: FfiConverterRustBuffer {
    typealias SwiftType = CryptoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CryptoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidInput(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .CryptoFailed(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CryptoError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidInput(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .CryptoFailed(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


extension CryptoError: Equatable, Hashable {}

extension CryptoError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceData: FfiConverterRustBuffer {
    typealias SwiftType = [Data]

    public static func write(_ value: [Data], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Data] {
        let len: Int32 = try readInt(&buf)
        var seq = [Data]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterData.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeBlindingEntry: FfiConverterRustBuffer {
    typealias SwiftType = [BlindingEntry]

    public static func write(_ value: [BlindingEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBlindingEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [BlindingEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [BlindingEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeBlindingEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSurjectionDomainEntry: FfiConverterRustBuffer {
    typealias SwiftType = [SurjectionDomainEntry]

    public static func write(_ value: [SurjectionDomainEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSurjectionDomainEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SurjectionDomainEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [SurjectionDomainEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSurjectionDomainEntry.read(from: &buf))
        }
        return seq
    }
}
public func computeBalancingBlindingFactorFullUniffi(value: UInt64, generatorBlindingFactor: Data, inputs: [BlindingEntry], otherOutputs: [BlindingEntry])throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_hathor_ct_crypto_fn_func_compute_balancing_blinding_factor_full_uniffi(
        FfiConverterUInt64.lower(value),
        FfiConverterData.lower(generatorBlindingFactor),
        FfiConverterSequenceTypeBlindingEntry.lower(inputs),
        FfiConverterSequenceTypeBlindingEntry.lower(otherOutputs),$0
    )
})
}
public func computeBalancingBlindingFactorUniffi(otherBlindingFactors: [Data])throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_hathor_ct_crypto_fn_func_compute_balancing_blinding_factor_uniffi(
        FfiConverterSequenceData.lower(otherBlindingFactors),$0
    )
})
}
public func createAssetCommitmentUniffi(tag: Data, blindingFactor: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_hathor_ct_crypto_fn_func_create_asset_commitment_uniffi(
        FfiConverterData.lower(tag),
        FfiConverterData.lower(blindingFactor),$0
    )
})
}
public func createShieldedOutputUniffi(value: UInt64, recipientPubkey: Data, tokenUid: Data, fullyShielded: Bool)throws  -> CreatedShieldedOutput {
    return try  FfiConverterTypeCreatedShieldedOutput.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_hathor_ct_crypto_fn_func_create_shielded_output_uniffi(
        FfiConverterUInt64.lower(value),
        FfiConverterData.lower(recipientPubkey),
        FfiConverterData.lower(tokenUid),
        FfiConverterBool.lower(fullyShielded),$0
    )
})
}
public func createShieldedOutputWithBlindingUniffi(value: UInt64, recipientPubkey: Data, tokenUid: Data, fullyShielded: Bool, blindingFactor: Data)throws  -> CreatedShieldedOutput {
    return try  FfiConverterTypeCreatedShieldedOutput.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_hathor_ct_crypto_fn_func_create_shielded_output_with_blinding_uniffi(
        FfiConverterUInt64.lower(value),
        FfiConverterData.lower(recipientPubkey),
        FfiConverterData.lower(tokenUid),
        FfiConverterBool.lower(fullyShielded),
        FfiConverterData.lower(blindingFactor),$0
    )
})
}
public func createShieldedOutputWithBothBlindingsUniffi(value: UInt64, recipientPubkey: Data, tokenUid: Data, valueBlindingFactor: Data, assetBlindingFactor: Data)throws  -> CreatedShieldedOutput {
    return try  FfiConverterTypeCreatedShieldedOutput.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_hathor_ct_crypto_fn_func_create_shielded_output_with_both_blindings_uniffi(
        FfiConverterUInt64.lower(value),
        FfiConverterData.lower(recipientPubkey),
        FfiConverterData.lower(tokenUid),
        FfiConverterData.lower(valueBlindingFactor),
        FfiConverterData.lower(assetBlindingFactor),$0
    )
})
}
public func createSurjectionProofUniffi(codomainTag: Data, codomainBlindingFactor: Data, domain: [SurjectionDomainEntry])throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_hathor_ct_crypto_fn_func_create_surjection_proof_uniffi(
        FfiConverterData.lower(codomainTag),
        FfiConverterData.lower(codomainBlindingFactor),
        FfiConverterSequenceTypeSurjectionDomainEntry.lower(domain),$0
    )
})
}
public func decryptShieldedOutputUniffi(recipientPrivkey: Data, ephemeralPubkey: Data, commitment: Data, rangeProof: Data, tokenUid: Data, assetCommitment: Data?)throws  -> DecryptedShieldedOutput {
    return try  FfiConverterTypeDecryptedShieldedOutput.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_hathor_ct_crypto_fn_func_decrypt_shielded_output_uniffi(
        FfiConverterData.lower(recipientPrivkey),
        FfiConverterData.lower(ephemeralPubkey),
        FfiConverterData.lower(commitment),
        FfiConverterData.lower(rangeProof),
        FfiConverterData.lower(tokenUid),
        FfiConverterOptionData.lower(assetCommitment),$0
    )
})
}
public func deriveAssetTagUniffi(tokenUid: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_hathor_ct_crypto_fn_func_derive_asset_tag_uniffi(
        FfiConverterData.lower(tokenUid),$0
    )
})
}
public func deriveEcdhSharedSecretUniffi(privkey: Data, pubkey: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_hathor_ct_crypto_fn_func_derive_ecdh_shared_secret_uniffi(
        FfiConverterData.lower(privkey),
        FfiConverterData.lower(pubkey),$0
    )
})
}
public func deriveRewindNonceUniffi(sharedSecret: Data) -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_hathor_ct_crypto_fn_func_derive_rewind_nonce_uniffi(
        FfiConverterData.lower(sharedSecret),$0
    )
})
}
public func deriveTagUniffi(tokenUid: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_hathor_ct_crypto_fn_func_derive_tag_uniffi(
        FfiConverterData.lower(tokenUid),$0
    )
})
}
public func getZeroTweakUniffi() -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_hathor_ct_crypto_fn_func_get_zero_tweak_uniffi($0
    )
})
}
public func htrAssetTagUniffi() -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_hathor_ct_crypto_fn_func_htr_asset_tag_uniffi($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_hathor_ct_crypto_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_compute_balancing_blinding_factor_full_uniffi() != 10926) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_compute_balancing_blinding_factor_uniffi() != 3945) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_create_asset_commitment_uniffi() != 41953) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_create_shielded_output_uniffi() != 24504) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_create_shielded_output_with_blinding_uniffi() != 11551) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_create_shielded_output_with_both_blindings_uniffi() != 5386) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_create_surjection_proof_uniffi() != 18457) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_decrypt_shielded_output_uniffi() != 54231) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_derive_asset_tag_uniffi() != 36682) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_derive_ecdh_shared_secret_uniffi() != 38759) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_derive_rewind_nonce_uniffi() != 61704) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_derive_tag_uniffi() != 39810) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_get_zero_tweak_uniffi() != 37883) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hathor_ct_crypto_checksum_func_htr_asset_tag_uniffi() != 40191) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all