"""Type stubs for the hathor_ct_crypto native module.

The implementations land in a later PR; until then the compiled module is
empty and any access fails at call time. These stubs describe the eventual
native API so that call sites type-check against it today.
"""

COMMITMENT_SIZE: int
GENERATOR_SIZE: int
ZERO_TWEAK: bytes

def derive_asset_tag(token_uid: bytes) -> bytes: ...
def htr_asset_tag() -> bytes: ...
def derive_tag(token_uid: bytes) -> bytes: ...
def create_asset_commitment(*, tag_bytes: bytes, r_asset: bytes) -> bytes: ...
def create_commitment(*, amount: int, blinding: bytes, generator: bytes) -> bytes: ...
def create_trivial_commitment(*, amount: int, generator: bytes) -> bytes: ...
def verify_commitments_sum(*, positive: list[bytes], negative: list[bytes]) -> bool: ...
def validate_commitment(data: bytes) -> bool: ...
def validate_generator(data: bytes) -> bool: ...
def create_range_proof(
    *,
    amount: int,
    blinding: bytes,
    commitment: bytes,
    generator: bytes,
    message: bytes | None = None,
    nonce: bytes | None = None,
) -> bytes: ...
def verify_range_proof(*, proof: bytes, commitment: bytes, generator: bytes) -> bool: ...
def rewind_range_proof(
    *,
    proof: bytes,
    commitment: bytes,
    nonce: bytes,
    generator: bytes,
) -> tuple[int, bytes, bytes]: ...
def create_surjection_proof(
    *,
    codomain_tag: bytes,
    codomain_blinding_factor: bytes,
    domain: list[tuple[bytes, bytes, bytes]],
) -> bytes: ...
def verify_surjection_proof(*, proof: bytes, codomain: bytes, domain: list[bytes]) -> bool: ...
def verify_balance(
    *,
    transparent_inputs: list[tuple[int, bytes]],
    shielded_inputs: list[bytes],
    transparent_outputs: list[tuple[int, bytes]],
    shielded_outputs: list[bytes],
    excess_blinding_factor: bytes | None = None,
) -> bool: ...
def compute_balancing_blinding_factor(
    *,
    value: int,
    generator_blinding_factor: bytes,
    inputs: list[tuple[int, bytes, bytes]],
    other_outputs: list[tuple[int, bytes, bytes]],
) -> bytes: ...
def generate_ephemeral_keypair() -> tuple[bytes, bytes]: ...
def derive_ecdh_shared_secret(*, private_key_bytes: bytes, peer_pubkey_bytes: bytes) -> bytes: ...
def derive_rewind_nonce(shared_secret: bytes) -> bytes: ...
