# SPDX-FileCopyrightText: Hathor Labs
# SPDX-License-Identifier: Apache-2.0

alias stop-hathord='sudo supervisorctl stop hathord'
alias start-hathord='sudo supervisorctl start hathord'
alias status-hathord='sudo supervisorctl status hathord'
alias restart-hathord='sudo supervisorctl restart hathord'
