# yamllint disable rule:line-length
name: benchmarking
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking base branch
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Install hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.12.0/hyperfine_1.12.0_amd64.deb
          sudo dpkg -i hyperfine_1.12.0_amd64.deb
      - uses: ./.github/actions/setup-hathor-env
        name: Setup Hathor node environment
        with:
          python: 3.11
          os: ubuntu-22.04
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project hathor-core \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch master \
          --testbed ubuntu-22.04 \
          --adapter shell_hyperfine \
          --err \
          --file bench_results.json \
          './extras/benchmarking/benchmark_sync_v2.sh'
